# Generated by Django 5.0.2 on 2025-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('demand', models.FloatField()),
                ('size', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
